#!/usr/bin/env bash
# loom installer — idempotent, safe to re-run (also serves as the upgrade path)
set -euo pipefail

LOOM_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export LOOM_DIR
CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/loom"
STATE_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/loom"
SKILLS_DIR="${HOME}/.claude/skills"
CLAUDE_SETTINGS="${HOME}/.claude/settings.json"

# ── Colours ────────────────────────────────────────────────────────────────
if [ -t 1 ]; then
  GREEN='\033[92m'; YELLOW='\033[93m'; RED='\033[91m'; BOLD='\033[1m'; RESET='\033[0m'
else
  GREEN=''; YELLOW=''; RED=''; BOLD=''; RESET=''
fi
ok()   { echo -e "${GREEN}✓${RESET} $*"; }
warn() { echo -e "${YELLOW}⚠${RESET} $*"; }
err()  { echo -e "${RED}✗${RESET} $*" >&2; exit 1; }
info() { echo "  $*"; }

echo -e "\n${BOLD}🧵 loom installer${RESET}"
echo "   Installing from: $LOOM_DIR"
echo ""

# ── Prerequisites ──────────────────────────────────────────────────────────
echo "Checking prerequisites…"

check_cmd() {
  if command -v "$1" &>/dev/null; then
    ok "$1 ($(command -v "$1"))"
  else
    if [ "${2:-required}" = "required" ]; then
      err "$1 not found — please install it first."
    else
      warn "$1 not found (optional, needed for: ${3:-some features})"
    fi
  fi
}

check_cmd python3 required
check_cmd tmux    required
check_cmd git     required
check_cmd notify-send optional "desktop notifications"
echo ""

# Verify Python version >= 3.8
PY_VER=$(python3 -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
PY_MAJOR=$(echo "$PY_VER" | cut -d. -f1)
PY_MINOR=$(echo "$PY_VER" | cut -d. -f2)
if [ "$PY_MAJOR" -lt 3 ] || { [ "$PY_MAJOR" -eq 3 ] && [ "$PY_MINOR" -lt 8 ]; }; then
  err "Python 3.8+ required (found $PY_VER)"
fi
ok "Python $PY_VER"
echo ""

# ── Config directory ───────────────────────────────────────────────────────
echo "Setting up config…"
mkdir -p "$CONFIG_DIR" "$STATE_DIR"

# Write LOOM_DIR pointer (used by hooks to locate the lib)
echo "$LOOM_DIR" > "$CONFIG_DIR/loom_dir"
ok "Wrote $CONFIG_DIR/loom_dir"

# Create default config if not exists
if [ ! -f "$CONFIG_DIR/config" ]; then
  VAULT_DEFAULT="$HOME/vault"
  if [ -t 0 ]; then
    read -r -p "  Vault directory [$VAULT_DEFAULT]: " VAULT_INPUT
    VAULT_PATH="${VAULT_INPUT:-$VAULT_DEFAULT}"
  else
    VAULT_PATH="$VAULT_DEFAULT"
    info "Non-interactive mode — using default vault: $VAULT_PATH"
  fi
  VAULT_PATH="${VAULT_PATH/#\~/$HOME}"

  # Generate a random web token so the UI is safe to expose beyond localhost
  WEB_TOKEN=$(python3 -c "import secrets; print(secrets.token_hex(16))")

  cat > "$CONFIG_DIR/config" <<EOF
# loom configuration
# Generated by install.sh — edit freely

LOOM_VAULT="$VAULT_PATH"
LOOM_SESSION_PREFIX="loom"
LOOM_WEB_PORT="7799"

# Bind address. Empty = automatic: 0.0.0.0 when a token is set, else 127.0.0.1
LOOM_WEB_BIND=""

# Web token (generated at install): required in the URL (?token=…) or as
# an Authorization: Bearer header. Clear it to force localhost-only.
LOOM_WEB_TOKEN="$WEB_TOKEN"

# Distillation: auto | manual | off
LOOM_DISTILL="auto"
LOOM_DISTILL_MODEL="claude-sonnet-4-5"

# Notifications: comma-separated list of: notify-send, ntfy, bell
LOOM_NOTIFICATIONS="notify-send"
# LOOM_NTFY_TOPIC="loom"
# LOOM_NTFY_SERVER="https://ntfy.sh"
# LOOM_WEB_URL=""             # public web-UI URL, used for notification click links

# Register Claude sessions started outside loom (1 = every session lands in the vault)
# LOOM_ADOPT_UNMANAGED="0"
# Desktop-notify every time a task finishes a turn
# LOOM_NOTIFY_ON_STOP="0"
EOF
  ok "Created $CONFIG_DIR/config"
else
  ok "Config already exists at $CONFIG_DIR/config (skipping)"
fi
echo ""

# ── PATH setup ─────────────────────────────────────────────────────────────
echo "Checking PATH…"
LOOM_BIN="$LOOM_DIR/bin"

path_has_loom() { echo "$PATH" | tr ':' '\n' | grep -qxF "$LOOM_BIN"; }

if path_has_loom; then
  ok "bin/ already in PATH"
else
  warn "bin/ not in PATH — adding to shell config"

  # Detect shell
  SHELL_RC=""
  case "${SHELL:-}" in
    */zsh)  SHELL_RC="$HOME/.zshrc" ;;
    */bash) SHELL_RC="$HOME/.bashrc" ;;
    *)      SHELL_RC="$HOME/.profile" ;;
  esac

  LINE="export PATH=\"$LOOM_BIN:\$PATH\""
  if ! grep -qF "$LOOM_BIN" "$SHELL_RC" 2>/dev/null; then
    echo "" >> "$SHELL_RC"
    echo "# loom" >> "$SHELL_RC"
    echo "$LINE" >> "$SHELL_RC"
    ok "Appended to $SHELL_RC"
    info "Run: source $SHELL_RC  (or open a new terminal)"
  else
    ok "Already referenced in $SHELL_RC"
  fi
fi
echo ""

# ── Skills symlinks ────────────────────────────────────────────────────────
echo "Linking skills to ~/.claude/skills/…"
mkdir -p "$SKILLS_DIR"

for skill_dir in "$LOOM_DIR/skills"/*/; do
  skill_name="$(basename "$skill_dir")"
  target="$SKILLS_DIR/$skill_name"
  if [ -L "$target" ]; then
    ok "Skill $skill_name already linked"
  elif [ -e "$target" ]; then
    warn "Skill $skill_name: $target exists but is not a symlink — skipping"
  else
    ln -s "$skill_dir" "$target"
    ok "Linked skill: $skill_name → $target"
  fi
done
echo ""

# ── Merge hooks into ~/.claude/settings.json ──────────────────────────────
echo "Installing Claude Code hooks…"

python3 - <<'PYEOF'
import json, os, sys
from pathlib import Path

loom_dir     = os.environ.get("LOOM_DIR", "")
template_path = Path(loom_dir) / "hooks" / "hooks-template.json"
settings_path = Path.home() / ".claude" / "settings.json"

if not template_path.exists():
    print(f"  Warning: hooks template not found at {template_path}")
    sys.exit(0)

# Load and substitute LOOM_DIR in template
template_text = template_path.read_text().replace("{{LOOM_DIR}}", loom_dir)
new_hooks     = json.loads(template_text).get("hooks", {})

# Load existing settings.json
if settings_path.exists():
    try:
        existing = json.loads(settings_path.read_text())
    except json.JSONDecodeError:
        existing = {}
else:
    settings_path.parent.mkdir(parents=True, exist_ok=True)
    existing = {}

# Deep merge: for each event, add our hooks (avoid duplicates by command)
current_hooks = existing.setdefault("hooks", {})
for event, entries in new_hooks.items():
    if event not in current_hooks:
        current_hooks[event] = entries
        print(f"  Added hooks for {event}")
    else:
        existing_cmds = set()
        for group in current_hooks[event]:
            for h in group.get("hooks", []):
                existing_cmds.add(h.get("command", ""))
        for entry in entries:
            new_cmds = [h.get("command","") for h in entry.get("hooks",[])]
            if not any(c in existing_cmds for c in new_cmds):
                current_hooks[event].append(entry)
                print(f"  Added hook to {event}")
            else:
                print(f"  Hook already present for {event} (skipping)")

settings_path.write_text(json.dumps(existing, indent=2))
print(f"  Wrote {settings_path}")
PYEOF

ok "Hooks installed"
echo ""

# ── Initialize vault ───────────────────────────────────────────────────────
echo "Initializing vault…"

# Re-read LOOM_VAULT from config
LOOM_VAULT=$(python3 -c "
import os, re
cfg = os.path.join(os.environ.get('XDG_CONFIG_HOME', os.path.expanduser('~/.config')), 'loom', 'config')
val = os.path.expanduser('~/vault')
try:
    for line in open(cfg):
        line = line.strip()
        if line.startswith('LOOM_VAULT='):
            val = line.split('=',1)[1].strip().strip('\"')
            val = os.path.expanduser(val)
            break
except FileNotFoundError:
    pass
print(val)
")
export LOOM_VAULT

if [ ! -d "$LOOM_VAULT/10-Tasks" ]; then
  python3 - <<'PYEOF'
import sys, os
sys.path.insert(0, os.path.join(os.environ.get("LOOM_DIR",""), "lib"))
from loom import Config, VaultManager
cfg = Config(); v = VaultManager(cfg); v.init()
print(f"  Initialized at {v.vault}")
PYEOF
  ok "Vault initialized at $LOOM_VAULT"
else
  ok "Vault already initialized at $LOOM_VAULT"
fi
echo ""

# ── Done ───────────────────────────────────────────────────────────────────
echo -e "${BOLD}${GREEN}Installation complete!${RESET}"
echo ""
echo "  Next steps:"
echo "  1. Open a new terminal (or: source your shell rc)"
echo "  2. loom new my-first-task"
echo "  3. loom web        (start the web UI)"
echo ""
echo "  Config: $CONFIG_DIR/config"
echo "  Vault:  $LOOM_VAULT"
echo ""
