#!/usr/bin/env bash
# loom gateway setup — run this on a fresh AWS/VPS instance (Ubuntu 22.04/24.04)
#
# Usage:
#   bash setup-gateway.sh \
#     --domain loom.yourdomain.com \
#     --email  you@example.com \
#     --password "choose-a-strong-password"
#
# What it does:
#   1. Installs nginx + certbot
#   2. Hardens SSH (no password auth, no root login)
#   3. Creates a dedicated 'loom-tunnel' system user for reverse tunnels
#   4. Generates Let's Encrypt TLS certificate
#   5. Writes nginx config with basic auth (proxy to tunnel ports)
#   6. Opens only ports 22 (SSH) and 443 (HTTPS)
#
# Each loom machine then connects with:
#   autossh -N -R <remote_port>:localhost:7799 loom-tunnel@<domain>
#
# Machine 1 → remote_port 17799  → https://loom.yourdomain.com/m1/
# Machine 2 → remote_port 17800  → https://loom.yourdomain.com/m2/
# (add machines 3+ by adding blocks in /etc/nginx/conf.d/loom.conf)

set -euo pipefail

# ── Parse args ──────────────────────────────────────────────────────────────
DOMAIN="" EMAIL="" PASSWORD=""
while [[ $# -gt 0 ]]; do
  case $1 in
    --domain)   DOMAIN="$2";   shift 2 ;;
    --email)    EMAIL="$2";    shift 2 ;;
    --password) PASSWORD="$2"; shift 2 ;;
    *) echo "Unknown: $1"; exit 1 ;;
  esac
done
[[ -z "$DOMAIN" || -z "$EMAIL" || -z "$PASSWORD" ]] && {
  echo "Usage: $0 --domain DOMAIN --email EMAIL --password PASSWORD"
  exit 1
}

info()  { echo -e "\033[92m✓\033[0m $*"; }
warn()  { echo -e "\033[93m⚠\033[0m $*"; }
err()   { echo -e "\033[91m✗\033[0m $*" >&2; exit 1; }

# Must run as root
[[ $EUID -eq 0 ]] || err "Run as root: sudo bash $0 ..."

# ── 1. System packages ───────────────────────────────────────────────────────
echo "Installing packages..."
apt-get update -qq
apt-get install -y -qq nginx certbot python3-certbot-nginx apache2-utils ufw autossh
info "Packages installed"

# ── 2. Firewall — only SSH and HTTPS ────────────────────────────────────────
ufw --force reset
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp    comment "SSH"
ufw allow 443/tcp   comment "HTTPS"
ufw --force enable
info "Firewall: only 22 (SSH) and 443 (HTTPS) open"

# ── 3. Harden SSH ────────────────────────────────────────────────────────────
# Disable password auth and root login (key-only)
sed -i 's/^#*PermitRootLogin.*/PermitRootLogin no/'          /etc/ssh/sshd_config
sed -i 's/^#*PasswordAuthentication.*/PasswordAuthentication no/' /etc/ssh/sshd_config
sed -i 's/^#*PubkeyAuthentication.*/PubkeyAuthentication yes/'   /etc/ssh/sshd_config
# Allow reverse tunnel forwarding (GatewayPorts needed for 127.0.0.1 binding)
grep -q "^GatewayPorts" /etc/ssh/sshd_config || echo "GatewayPorts clientspecified" >> /etc/ssh/sshd_config
systemctl reload sshd
info "SSH hardened (key-only, no root)"

# ── 4. Dedicated tunnel user ─────────────────────────────────────────────────
# This user can only create tunnels — no shell, no home writes
if ! id loom-tunnel &>/dev/null; then
  useradd -r -s /bin/false -m -d /var/lib/loom-tunnel loom-tunnel
fi
TUNNEL_HOME=/var/lib/loom-tunnel
mkdir -p "$TUNNEL_HOME/.ssh"
chmod 700 "$TUNNEL_HOME/.ssh"

if [[ ! -f "$TUNNEL_HOME/.ssh/authorized_keys" ]]; then
  touch "$TUNNEL_HOME/.ssh/authorized_keys"
  chmod 600 "$TUNNEL_HOME/.ssh/authorized_keys"
fi
chown -R loom-tunnel:loom-tunnel "$TUNNEL_HOME"
info "Tunnel user 'loom-tunnel' created"
echo ""
warn "Next step: copy each machine's SSH public key into:"
warn "  $TUNNEL_HOME/.ssh/authorized_keys"
warn "  (prefix each key with: restrict,port-forwarding)"
echo ""

# ── 5. Basic-auth password file ──────────────────────────────────────────────
htpasswd -bc /etc/nginx/loom.htpasswd loom "$PASSWORD"
chmod 640 /etc/nginx/loom.htpasswd
info "Basic auth: user=loom, password=<set>"

# ── 6. TLS certificate ───────────────────────────────────────────────────────
# Temporarily serve plain HTTP for the ACME challenge
cat > /etc/nginx/sites-available/loom-acme << 'EOF'
server { listen 80; server_name _; location /.well-known { root /var/www/html; } }
EOF
ln -sf /etc/nginx/sites-available/loom-acme /etc/nginx/sites-enabled/loom-acme
rm -f /etc/nginx/sites-enabled/default
nginx -t && systemctl restart nginx

certbot certonly --nginx --non-interactive --agree-tos \
  -m "$EMAIL" -d "$DOMAIN"
info "TLS certificate issued for $DOMAIN"

# ── 7. nginx config ───────────────────────────────────────────────────────────
rm -f /etc/nginx/sites-enabled/loom-acme

cat > /etc/nginx/conf.d/loom.conf << EOF
# loom gateway — generated by setup-gateway.sh
# Add a new 'location /mN/' block for each machine.

map \$http_upgrade \$connection_upgrade {
    default upgrade;
    ''      close;
}

server {
    listen 443 ssl http2;
    server_name ${DOMAIN};

    ssl_certificate     /etc/letsencrypt/live/${DOMAIN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${DOMAIN}/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    # Password protection for the whole site
    auth_basic           "loom";
    auth_basic_user_file /etc/nginx/loom.htpasswd;

    # Machine 1 — tunnel port 17799
    location /m1/ {
        proxy_pass         http://127.0.0.1:17799/;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade    \$http_upgrade;
        proxy_set_header   Connection \$connection_upgrade;
        proxy_set_header   Host       \$host;
        proxy_read_timeout 300s;
    }

    # Machine 2 — tunnel port 17800
    location /m2/ {
        proxy_pass         http://127.0.0.1:17800/;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade    \$http_upgrade;
        proxy_set_header   Connection \$connection_upgrade;
        proxy_set_header   Host       \$host;
        proxy_read_timeout 300s;
    }

    # Redirect HTTP to HTTPS
    error_page 497 https://\$host\$request_uri;
}

server {
    listen 80;
    server_name ${DOMAIN};
    return 301 https://\$host\$request_uri;
}
EOF

nginx -t && systemctl reload nginx
info "nginx configured for https://${DOMAIN}/m1/ and /m2/"

# ── 8. Auto-renew certs ───────────────────────────────────────────────────────
(crontab -l 2>/dev/null; echo "0 3 * * * certbot renew --quiet && systemctl reload nginx") | crontab -
info "certbot auto-renew scheduled"

# ── Done ─────────────────────────────────────────────────────────────────────
echo ""
echo "════════════════════════════════════════════════════════════"
echo "  Gateway ready at https://${DOMAIN}"
echo "  User: loom  |  Password: (what you set)"
echo ""
echo "  On each loom machine:"
echo "  1. Add machine's SSH pubkey to:"
echo "     ${TUNNEL_HOME}/.ssh/authorized_keys"
echo "     (prefix with: restrict,port-forwarding )"
echo ""
echo "  2. Set in ~/.config/loom/config:"
echo "     LOOM_GATEWAY_HOST=${DOMAIN}"
echo "     LOOM_GATEWAY_USER=loom-tunnel"
echo "     LOOM_GATEWAY_PORT=17799  # 17800 for machine 2, etc."
echo ""
echo "  3. Run: loom tunnel enable"
echo "════════════════════════════════════════════════════════════"
